FROM ubuntu:22.04 as linux

RUN apt update
RUN apt install -y wget curl

RUN curl -fsSL https://deb.nodesource.com/setup_16.x | bash -
RUN apt install -y nodejs

RUN wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
RUN apt install ./google-chrome*.deb -y

WORKDIR /app
COPY . .

RUN npm install

ENTRYPOINT ["npm", "run", "test:ci"]